testMode: True

gaWithSurrogateAlgoParams:
  numEvals: 1500
  numIndividuals: 11
  mutationType: psm
  crossoverType: blend_crossover
  selectionType: fitness_prop
  crossAlpha: 0.5046
  bestProc: 0.4439
  elemCrossProb: None