---
apiVersion: batch/v1
kind: Job
metadata:
  name: autotm
  labels:
    app: autotm
spec:
  template:
    metadata:
      labels:
        app: autotm
      annotations:
        "sidecar.istio.io/inject": "false"
    spec:
      volumes:
        - name: varlog
          emptyDir: { }
      containers:
      - name: autom-job
        image: node2.bdcl:5000/autotm-job:latest
        imagePullPolicy: Always
        args: ["--dataset", "clickhouse_issues",
               "--num-individuals", "11",
               "--num-iterations", "20",
               "--mutation-type", "psm",
               "--crossover-type", "blend_crossover",
               "--selection-type", "fitness_prop",
               "--cross-alpha", "0.5046",
               "--best-proc", "0.4439",
               "--log-file", "/var/log/tm-alg-ga-clickhouse.txt",
               "--exp-id", "27",
               "--topic-count", "50"]
        env:
          - name: CELERY_BROKER_URL
            value: "amqp://guest:guest@rabbitmq-service:5672"
          - name: CELERY_RESULT_BACKEND
            value: "redis://redis:6379/1"
          - name: FITNESS_CONFIG_PATH
            value: /app/algorithms_for_tuning/genetic_algorithm/config.yaml
        volumeMounts:
          - name: varlog
            mountPath: /var/log/
#      - name: alglog
#        image: busybox
#        imagePullPolicy: IfNotPresent
#        args: [ /bin/sh, -c, 'sleep 15 && tail -n+1 -f /var/log/repeater.log' ]
#        volumeMounts:
#          - name: varlog
#            mountPath: /var/log
      restartPolicy: Never
  backoffLimit: 0
