---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: repeater-checkpoints-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/ess_storage/DN_1/storage/home/khodorchenko/repeater-checkpoints
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: repeater-checkpoints-pvc
spec:
  storageClassName: manual
  volumeName: repeater-checkpoints-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
