---
apiVersion: batch/v1
kind: Job
metadata:
  name: repeater
spec:
  template:
    metadata:
      annotations:
        "sidecar.istio.io/inject": "false"
    spec:
      volumes:
        - name: repeater-checkpoints
          persistentVolumeClaim:
            claimName: repeater-checkpoints-pvc
        - name: varlog
          emptyDir: { }
      containers:
      - name: repeater
        image: node2.bdcl:5000/exp-repeater:latest
        imagePullPolicy: Always
        args: ["--config", "repeater-config.yaml",
               "--checkpoint-dir", "/var/lib/repeater/",
               "--runs-log-dir", "/var/lib/repeater/logs",
               "--parallel", "100"]
        env:
          - name: CELERY_BROKER_URL
            value: "amqp://guest:guest@rabbitmq-service:5672"
          - name: CELERY_RESULT_BACKEND
            value: "redis://redis:6379/1"
          - name: FITNESS_CONFIG_PATH
            value: "/app/irace_config/config.yaml"
        volumeMounts:
          - name: repeater-checkpoints
            mountPath: /var/lib/repeater/
          - name: varlog
            mountPath: /var/log/
#      - name: alglog
#        image: busybox
#        imagePullPolicy: IfNotPresent
#        args: [ /bin/sh, -c, 'sleep 15 && tail -n+1 -f /var/log/repeater.log' ]
#        volumeMounts:
#          - name: varlog
#            mountPath: /var/log
      restartPolicy: Never
  backoffLimit: 0
