testMode: False

gaAlgoParams:
  numEvals: 150

deAlgoParams:
  numEvals: 150

abcAlgoParams:
  numEvals: 150
  problemDim: 16

boAlgoParams:
  numEvals: 150

gaWithSurrogateAlgoParams:
  numEvals: 150
  numIndividuals: 11
  mutationType: psm
  crossoverType: blend_crossover
  selectionType: fitness_prop
  crossAlpha: 0.5046
  bestProc: 0.4439
  elemCrossProb: None
