testMode: False

gaAlgoParams:
  numEvals: 150

deAlgoParams:
  numEvals: 150

abcAlgoParams:
  numEvals: 150
  problemDim: 16

boAlgoParams:
  numEvals: 150

rfSurAlgoParams:
  numEvals: 150

mlpSurAlgoParams:
  numEvals: 150