##################
#### MLFlow
##################
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "autotm.prefix" . }}mlflow-mysql-cnf
  labels:
    {{- range $key, $val := .Values.required_labels }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
data:
  my.cnf: |
    [mysqld]
    max_connections=500
    wait_timeout=15
    interactive_timeout=15
    thread_pool_size=32
##################
#### Celery & Fitness Workers
##################
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "autotm.prefix" . }}rabbitmq-config
  labels:
    {{- range $key, $val := .Values.required_labels }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
data:
  consumer-settings.conf: |
    ## Consumer timeout
    ## If a message delivered to a consumer has not been acknowledge before this timer
    ## triggers the channel will be force closed by the broker. This ensure that
    ## faultly consumers that never ack will not hold on to messages indefinitely.
    ##
    consumer_timeout = 1800000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "autotm.prefix" . }}worker-config
  labels:
    {{- range $key, $val := .Values.required_labels }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
data:
  datasets-config.yaml: |
{{ .Values.worker_datasets_config_content | indent 4}}
