appName: geneticAlgo
logLevel: WARN

testMode: True

paths:
  logFile: "logs"

abcAlgoParams:
  numEvals: 20
  problemDim: 16

datasets:
  20newsgroups:
    base_path: "./resources/20newsgroups"
    topic_count: 20
