---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-db-phpmyadmin
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    app: mlflow-db-phpmyadmin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-db-phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-db-phpmyadmin
  template:
    metadata:
      annotations:
        "sidecar.istio.io/inject": "false"
      labels:
        app: mlflow-db-phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin:5.1.1
        imagePullPolicy: IfNotPresent
        env:
          - name: PMA_HOST
            value: mlflow-db
          - name: PMA_PORT
            value: "3306"
          - name: PMA_USER
            value: mlflow
          - name: PMA_PASSWORD
            value: mlflow
        ports:
        - containerPort: 80
