apiVersion: batch/v1
kind: Job
metadata:
  name: fitness-client
spec:
  template:
# works even with injection
    metadata:
      annotations:
        "sidecar.istio.io/inject": "false"
    spec:
      containers:
      - name: client
        image: node2.bdcl:5000/fitness-client:latest
        args: ["test"]
        imagePullPolicy: Always
        env:
          - name: CELERY_BROKER_URL
            value: "amqp://guest:guest@rabbitmq-service:5672"
          - name: CELERY_RESULT_BACKEND
            value: "redis://redis:6379/1" # "rpc://"
      restartPolicy: Never
  backoffLimit: 0