# TODO: need to be fixed in mongo part
#---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: mlflow-db-pv
#spec:
#  storageClassName: manual
#  capacity:
#    storage: 25Gi
#  volumeMode: Filesystem
#  accessModes:
#    - ReadWriteOnce
#  persistentVolumeReclaimPolicy: Retain
#  local:
#    path: /data/hdd/mlflow-db
#  nodeAffinity:
#    required:
#      nodeSelectorTerms:
#        - matchExpressions:
#            - key: kubernetes.io/hostname
#              operator: In
#              values:
#                - localhost.localdomain
#---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: mlflow-artifact-store-pv
#spec:
#  storageClassName: manual
#  capacity:
#    storage: 50Gi
#  volumeMode: Filesystem
#  accessModes:
#    - ReadWriteMany
#  persistentVolumeReclaimPolicy: Retain
#  hostPath:
#    path: /mnt/ess_storage/DN_1/storage/home/khodorchenko/mlflow-tm-experiments/mlflow-artifact-store
#    type: Directory
#---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: mongo-tm-experiments-pv
#spec:
#  storageClassName: manual
#  capacity:
#    storage: 20Gi
#  volumeMode: Filesystem
#  accessModes:
#    - ReadWriteOnce
#  persistentVolumeReclaimPolicy: Retain
#  hostPath:
#    path: /mnt/ess_storage/DN_1/storage/home/khodorchenko/mlflow-tm-experiments/mongodb
#    type: Directory
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: mlflow-db-pvc
#spec:
#  storageClassName: manual
#  volumeName: mlflow-db-pv
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 25Gi
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: mlflow-artifact-store-pvc
#spec:
#  storageClassName: manual
#  volumeName: mlflow-artifact-store-pv
#  accessModes:
#    - ReadWriteMany
#  resources:
#    requests:
#      storage: 25Gi
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: mongo-tm-experiments-pvc
#spec:
#  storageClassName: manual
#  volumeName: mongo-tm-experiments-pv
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 20Gi
