appName: geneticAlgo
logLevel: WARN

testMode: True
datasetName: "lenta_ru"

paths:
  logFile: "logs"

globalAlgoParams:
  numEvals: 150

datasets:
  20newsgroups:
    base_path: "./resources/20newsgroups"
    topic_count: 20
