---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
data:
  consumer-settings.conf: |
    ## Consumer timeout
    ## If a message delivered to a consumer has not been acknowledge before this timer
    ## triggers the channel will be force closed by the broker. This ensure that
    ## faultly consumers that never ack will not hold on to messages indefinitely.
    ##
    consumer_timeout = 1800000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fitness-worker-config
data:
  datasets-config.yaml: |
    {{ datasets_config_content | indent( width=4, first=False) }}
