##################
#### MLFlow
##################
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-db-pvc
spec:
  storageClassName: manual
  volumeName: mlflow-db-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-artifact-store-pvc
spec:
  storageClassName: manual
  volumeName: mlflow-artifact-store-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 25Gi
##################
#### Mongo
##################
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-tm-experiments-pvc
spec:
  storageClassName: manual
  volumeName: mongo-tm-experiments-pv-part3
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
##################
#### Celery & Fitness Workers
##################
# TODO: redis & rabbitmq
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc
spec:
  storageClassName: manual
  volumeName: rabbitmq-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  storageClassName: manual
  volumeName: redis-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
