---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: {{ .Values.user }}
  name: pv-{{- .Values.user }}
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  mountOptions:
    - relatime
  nfs:
    path: /nfs_storage/home/{{- .Values.user }}
    readOnly: no
    server: 10.32.7.103
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.user }}
  name: pvc-{{- .Values.user }}
spec:
  volumeName: pv-{{- .Values.user }}
  storageClassName: slow
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: {{ .Values.user }}
  name: pv-shared-{{- .Values.user }}
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  mountOptions:
    - relatime
  nfs:
    path: /nfs_storage/shared
    readOnly: no
    server: 10.32.7.103
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.user }}
  name: pvc-shared-{{- .Values.user }}
spec:
  volumeName: pv-shared-{{- .Values.user }}
  storageClassName: slow
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Gi
