##################
#### MLFlow
##################
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "autotm.prefix" . }}mlflow-db-pvc
spec:
  storageClassName: manual
  volumeName: mlflow-db-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "autotm.prefix" . }}mlflow-artifact-store-pvc
spec:
  storageClassName: manual
  volumeName: mlflow-artifact-store-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 25Gi
##################
#### Mongo
##################
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "autotm.prefix" . }}mongo-tm-experiments-pvc
spec:
  storageClassName: manual
  volumeName: mongo-tm-experiments-pv-part3
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
