##################
#### MLFlow
##################
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "autotm.prefix" . }}mlflow-db-pvc
spec:
  storageClassName: manual
  volumeName: {{ .Values.pv_mlflow_db }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "autotm.prefix" . }}mlflow-artifact-store-pvc
spec:
  storageClassName: manual
  volumeName: {{ .Values.pv_mlflow_artifact_store }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 25Gi
##################
#### Mongo
##################
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "autotm.prefix" . }}mongo-tm-experiments-pvc
spec:
  storageClassName: manual
  volumeName: {{ .Values.pv_mongo_db }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
