##################
#### MLFlow
##################
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "autotm.prefix" . }}mlflow-db-phpmyadmin
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    app: {{ include "autotm.prefix" . }}mlflow-db-phpmyadmin
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "autotm.prefix" . }}mlflow-db
spec:
  ports:
  - port: 3306
  selector:
    app: {{ include "autotm.prefix" . }}mlflow-db
##################
#### Mongo
##################
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "autotm.prefix" . }}mongo-tm-experiments-db
spec:
  type: NodePort
  ports:
  - port: 27017
  selector:
    app: {{ include "autotm.prefix" . }}mongo-tm-experiments-db
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "autotm.prefix" . }}mongo-express
spec:
  type: NodePort
  ports:
  - port: 8081
  selector:
    app: {{ include "autotm.prefix" . }}mongo-express-tm-experiments
##################
#### Celery & Fitness Workers
##################
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "autotm.prefix" . }}rabbitmq-service
spec:
  ports:
  - port: 5672
  selector:
    app: {{ include "autotm.prefix" . }}rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "autotm.prefix" . }}redis
spec:
  ports:
  - port: 6379
  selector:
    app: {{ include "autotm.prefix" . }}redis
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "autotm.prefix" . }}celery-flower-service
spec:
  type: NodePort
  ports:
  - port: 5555
  selector:
    app: {{ include "autotm.prefix" . }}celery-flower
