---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  ports:
  - port: 5672
  selector:
    app: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
  - port: 6379
  selector:
    app: redis
---
apiVersion: v1
kind: Service
metadata:
  name: celery-flower-service
spec:
  type: NodePort
  ports:
  - port: 5555
  selector:
    app: celery-flower
