### General section
autotm_prefix: &autom_prefix "autotm"
required_labels:
  owner: *autom_prefix

### Images
# pull policy
pull_policy: "IfNotPresent"
worker_image_pull_policy: "Always"
# images
mysql_image: "mysql/mysql-server:5.7.28"
phpmyadmin_image: "phpmyadmin:5.1.1"
mongo_image: "mongo:4.4.6-bionic"
mongoexpress_image: "mongo-express:latest"
rabbitmq_image: "node2:bdcl:5000/rabbitmq:3:8-management-alpine"
redis_image: "node2.bdcl:5000/redis:6.2"
mlflow_image: "node2.bdcl:5000/mlflow-webserver:latest"
flower_image: "node2.bdcl:5000/flower:latest"
worker_image: "node2.bdcl:5000/fitness-worker:latest"

### Volumes
storage_class: "manual"
pv_mlflow_db: "mlflow-db-pv"
pv_mlflow_artifact_store: "mlflow-artifact-store-pv"
pv_mongo_db: "mongo-tm-experiments-pv-part3"
pv_dataset_store: "fitness-dataset-store=pv"

### Mlflow
mlflow_mysql_database: "mlflow"
mlflow_mysql_user: "mlflow"
mlflow_mysql_password: "mlflow"
mlflow_mysql_root_password: "mlflow"

### Mongo
mongo_user: "mongoadmin"
mongo_password: "secret"

### Fitness Worker settings
worker_datasets_dir_path: "/storage"
worker_count: 1
worker_cpu: 1
worker_mem: "8Gi"
worker_mongo_collection: "tm_stats"
worker_datasets_config_content: |
  datasets:
    # the rest settings will be the same as for the first dataset but will be added automatically
    books_stroyitelstvo_2030:
      base_path: "/storage/books_stroyitelstvo_2030_sample"
      topic_count: 10

    20newsgroups:
      base_path: "/storage/20newsgroups_sample"
      topic_count: 20

    clickhouse_issues:
      base_path: "/storage/clickhouse_issues_sample"
      labels: yes
      topic_count: 50

    # the rest settings will be the same as for the first dataset but will be added automatically
    banners:
      base_path: "/storage/banners_sample"
      topic_count: 20

    amazon_food:
      base_path: "/storage/amazon_food_sample"
      topic_count: 20

    hotel-reviews:
      base_path: "/storage/hotel-reviews_sample"
      topic_count: 20

    lenta_ru:
      base_path: "/storage/lenta_ru_sample"
      topic_count: 20
