---
datasets:
  - 20newsgroups
  - ads_data
  - amazon_food
  - hotel-reviews
  - lenta_ru

configurations:
#  - name: "ga_best_solution_1"
#    cmd: "/app/irace_config/ga_test/run.sh"
#    args: "--num-individuals 11 --mutation-type psm --crossover-type blend_crossover
#           --selection-type fitness_prop  --cross-alpha 0.5046 --best-proc 0.4439
#           --log-file /var/log/tm-alg-ga.txt --exp-id 5"
#    workdir: "/app/irace_config/ga_test"
#    repetitions: 30
#  - name: "abc_best_solution_1"
#    cmd: "/app/irace_config/abc_config/run.sh"
#    args: "--num-individuals 21 --max-num-trials 9
#           --init-method latin_hypercube --log-file /var/log/tm-alg-abc.txt
#           --exp-id 6"
#    workdir: "/app/irace_config/abc_config"
#    repetitions: 30
#  - name: "bo_best_solution_1"
    cmd: "/app/irace_config/bo_config/run.sh"
    args: "--log-file /var/log/tm-alg-ga.txt --exp-id 7"
    workdir: "/app/irace_config/bo_config"
    repetitions: 30
