---
datasets:
#  - books_stroyitelstvo_2030
  - 20newsgroups
#  - clickhouse_issues
  - banners
  - amazon_food
  - hotel-reviews
  - lenta_ru

configurations:
  - name: "ga_10"
    cmd: "/app/run-autotm.sh"
    args: "--num-individuals 11 --num-iterations 500 --mutation-type psm --crossover-type blend_crossover
           --selection-type fitness_prop  --cross-alpha 0.5046 --best-proc 0.4439
           --exp-id 31 --tag full_fitness_500_old_cross --topic-count 10"
    workdir: "/app"
    repetitions: 5

  - name: "ga_25"
    cmd: "/app/run-autotm.sh"
    args: "--num-individuals 11 --num-iterations 500 --mutation-type psm --crossover-type blend_crossover
           --selection-type fitness_prop  --cross-alpha 0.5046 --best-proc 0.4439
           --exp-id 31 --tag full_fitness_500_old_cross --topic-count 25"
    workdir: "/app"
    repetitions: 5

  - name: "ga_50"
    cmd: "/app/run-autotm.sh"
    args: "--num-individuals 11 --num-iterations 500 --mutation-type psm --crossover-type blend_crossover
           --selection-type fitness_prop  --cross-alpha 0.5046 --best-proc 0.4439
           --exp-id 31 --tag full_fitness_500_old_cross --topic-count 50"
    workdir: "/app"
    repetitions: 5

  - name: "ga_75"
    cmd: "/app/run-autotm.sh"
    args: "--num-individuals 11 --num-iterations 500 --mutation-type psm --crossover-type blend_crossover
           --selection-type fitness_prop  --cross-alpha 0.5046 --best-proc 0.4439
           --exp-id 31 --tag full_fitness_500_old_cross --topic-count 75"
    workdir: "/app"
    repetitions: 5

  - name: "ga_100"
    cmd: "/app/run-autotm.sh"
    args: "--num-individuals 11 --num-iterations 500 --mutation-type psm --crossover-type blend_crossover
           --selection-type fitness_prop  --cross-alpha 0.5046 --best-proc 0.4439
           --exp-id 31 --tag full_fitness_500_old_cross --topic-count 100"
    workdir: "/app"
    repetitions: 5
